export interface listEntry {
  id: number; // no usage, generated by jhipster
  itemName: string; //Could be album or single track
  itemURI: string; //Could be album or single track
  artistName: string;
  albumName?: string; //if it is track, album name, if not then empty
  reviewsCount: number;
  rating: number; // float number form 0 to 5
  addTime: Date;
  releaseTime: Date;
  imgURL?: string; //Album Cover image
  isFocus?: boolean;
}
